default:
  http_metas:
    content-type: text/html

  metas:
    title:        FBI Fugitive Concentration
    robots:       index, follow
    description:  FBI Fugitive Concentration
    keywords:     fbi, fugitive, concentration
    language:     en

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
